### ISSUE TITLE
 No module named dump_worksheet

### ISSUE THREAD

**Issue by erralb** [wichert/po-xls#10] opened 2017-09-29 12:33 UTC
Hello, I'm trying to use your program but I run into this error : 
```

$ po-to-xls en_GB.po
Traceback (most recent call last):
  File "/usr/local/bin/po-to-xls", line 11, in <module>
    load_entry_point('poxls==1.4.2', 'console_scripts', 'po-to-xls')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/poxls/po_to_xls.py", line 6, in <module>
ImportError: No module named dump_worksheet
```

After some googling it seems this module is a part of : openpyxl, which I have installed : 
```

$ sudo pip install openpyxl      
Requirement already satisfied: openpyxl in /usr/local/lib/python2.7/dist-packages/openpyxl-2.5.0a3-py2.7.egg
Requirement already satisfied: et_xmlfile in /usr/local/lib/python2.7/dist-packages/et_xmlfile-1.0.1-py2.7.egg (from openpyxl)
Requirement already satisfied: jdcal in /usr/local/lib/python2.7/dist-packages/jdcal-1.3-py2.7.egg (from openpyxl)

```

Would you have an idea on how to solve the problem? I am Using : Debian GNU/Linux buster/sid 64-bit

**Comment by rimi-itk** [comment] 2017-10-24 20:57
It seems that `po-xls` depends on openpyxl 2.4.*, e.g. [2.4.9](https://bitbucket.org/openpyxl/openpyxl/src/2b77055eecb3999de3e28fa623838c2db9a25b2d/?at=2.4.9).

Use
```
sudo pip install openpyxl==2.4.9
```
to install this exact version of openpyxl.

**Comment by AlmogCohen** [comment] 2018-07-07 15:00
Hmmm, not sure that this dependency is required anymore (the 2.4.*) as `openpyxl` specifically try and import the `WriteOnlyCell` from the proper place if the `openpyxl` version is higher than 2.5.0

**Comment by AlmogCohen** [comment] 2018-07-07 15:02
Initially I had the exact same issue, I followed your advice and all worked perfectly. Then, trying to submit a PR I was unable to reproduce the exception with `openpyxl` version `2.5.4`. Not sure what happened there.

**Comment by matthiask** [comment] 2019-01-31 15:07
This problem has already been fixed in https://github.com/wichert/po-xls/commit/24b7c5c2e05164acd8d752f537ed8e8d72d2ed79

**Comment by wichert** [comment] 2019-11-10 08:43
I've release version 1.5.0 which includes this fix.

**Closed by wichert** 2019-11-10 08:43 UTC
